### ISSUE TITLE
Typetura - Wordpress error after installing

### ISSUE THREAD

**Issue by antonijo01** [Typetura/Typetura#102]
I get error after instaling Typetura in Wordpress 6.4.

![image](https://github.com/Typetura/Typetura/assets/107608985/6977e8f4-a619-488e-aa86-a41c97397a9b)

**Comment by scottkellum** [comment]
Thank you so much for the bug report! I'll work to replicate this over the next few days.

**Comment by scottkellum** [comment]
I’m so sorry @antonijo01 but I’ve been over extended lately. I’m sunsetting the Wordpress plugin.
