### ISSUE TITLE
Keyboarding feature requests for Editor

### ISSUE THREAD

**Issue by WestonThayer** [Typetura/Typetura#14]
Great work! I wanted to jot some keyboard shortcuts for the Editor that I hoped worked:

- Features from Chrome Inspector:
    - Increment/decrement by integers with `ꜛ` and `↓` arrow keys
    - Increment/decrement by 0.1 with `⌥` and the arrow keys
    - Increment/decrement by 10 with `SHIFT` and the arrow keys
    - Increment/decrement by 100 with `⌘` and the arrow keys
- Features from After Effects
    - Hold `SHIFT` while dragging the viewport width to "snap" to existing keyframes

**Comment by WestonThayer** [comment]
Not keyboarding, but Sketch also has a feature where you can treat measurement labels as sliders, which is great for quickly eyeballing values:

![flash](https://user-images.githubusercontent.com/709153/48727137-36407700-ebe6-11e8-8169-a43519b57165.gif)

**Comment by scottkellum** [comment]
We’re tabling the app for now, so I’m closing this issue. When we get back to the app we will look through these issues
