### ISSUE TITLE
Check and mark invalid values

### ISSUE THREAD

**Issue by astearns** [Typetura/Typetura#15]
If you enter invalid values like font-size without a unit (not that I would ever do anything like that), the UI doesn't give you any feedback on why things aren't working as expected

![image](https://user-images.githubusercontent.com/1380751/48729946-d5b53800-ebed-11e8-8116-3084fcb289f9.png)

**Comment by scottkellum** [comment]
We’re tabling the app for now, so I’m closing this issue. When we get back to the app we will look through these issues
