### ISSUE TITLE
Relative unit interpolation in Safari

### ISSUE THREAD

**Issue by scottkellum** [Typetura/Typetura#18]
Em units self-compound and rem units are calculated incorrectly on initial load (rem issue is solved in the JS).

em issue is being tracked here: https://bugs.webkit.org/show_bug.cgi?id=194749
rem issue is being tracked here: https://bugs.webkit.org/show_bug.cgi?id=194765

**Comment by scottkellum** [comment]
The rem issue is solved in Safari’s dev channel

**Comment by davelab6** [comment]
Can this now be closed?
