### ISSUE TITLE
Single Resize Observer

### ISSUE THREAD

**Issue by kolodziejczak-sz** [Typetura/Typetura#70]
[this](https://github.com/WICG/resize-observer/issues/59) thread shows that having one ResizeObserver and watching multiple DOM elements is more performant than having ResizeObserver for each element. Just out of curiosity, is there any particular reason why you guys are using multiple ResizeObservers?

**Comment by scottkellum** [comment]
Because I was not aware of this thread. Thank you!

**Comment by scottkellum** [comment]
We’re removing JS from Typetura entirely. All CSS now.
