### ISSUE TITLE
Include Typetura with webpack

### ISSUE THREAD

**Issue by Starraider** [Typetura/Typetura#71]
Hi!
I tried to include Typetura with **webpack** on my website.

First I tried to include Typeture from the node_modules version with:
`import 'typeturajs';`
But this is not working at all.

Then I copied typetura.js into my assets folder and imported it like this:
`import './assets/js/typetura.js'`
This time it works with the viewport as context perfectly. But no matter how I tried to configure other contexts, it just ignores them (even the .typetura class)!
I put this in my app.js:
`
  window.typetura = {
    selectors: [
      ':root',
      '.typetura',
      'article',
      'section',
      'aside',
    ]
  };
  import './assets/js/typetura.js'
`

How can you configure other contexts with webpack??
Any idea?

**Comment by kolodziejczak-sz** [comment]
your webpack configuration probably bundles all files into one, that is why your import statement lands first and your custom config is being ignored. If I'm not mistaken (please share your webpack.config & index.html), one way to configure the typetura would be to edit index.html file and provide custom script before the webpack bundle, just like the documentation says:
```
<script>
  window.typetura = { selectors: ['div'] };
</script>

...

<script src="/main.webpack.bundle.js"></script>
```

**Comment by Starraider** [comment]
Even if I put the config in a custom script and place it infront of the webpack-bundle, it's still not working.
And btw. shouldn't it at least work with a .typetura class, even if there is no extra config?? But it's not working even with the .typetura class.

There is nothing special in my webpack.config.js:
`
var Encore = require('@symfony/webpack-encore')
const path = require('path')

Encore
  .setOutputPath(
    '../public/typo3conf/ext/customer_sitepackage/Resources/Public/'
  )
  .setPublicPath('/typo3conf/ext/customer_sitepackage/Resources/Public/')

  .configureFontRule({
    type: 'asset',
  })

  // Copy some static images
  .copyFiles([
    {
      from: './images',
      to: 'Images/[path][name].[ext]',
      includeSubdirectories: false,
      pattern: /\.(png|jpg|jpeg|svg)$/,
    }
  ])
  .configureImageRule({
    // tell Webpack it should consider inlining
    type: 'asset',
  })

  .addEntry('app', './js/app.js')
  .addEntry('head', './js/head.js')

  .enableSingleRuntimeChunk()
  .cleanupOutputBeforeBuild()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction())
  .enableSassLoader()
  .enablePostCssLoader()
  .splitEntryChunks()

module.exports = Encore.getWebpackConfig()
`

My head.js (which is placed in the head section of the html file) looks just like this:
`
import './Typetura/typetura'
`

(I can't provide you the index.html because it's generated by the CMS (TYPO3).

**Comment by scottkellum** [comment]
On your rendered web page do you see Typetura loaded in the head? It still sounds like it's not being rendered there. It needs to be there so it can watch the DOM as it populates.

Another possible issue: are you using an SPA or page that needs client side hydration?

**Comment by scottkellum** [comment]
We’re removing JS from Typetura entirely. All CSS now.
